apiVersion: v1
kind: Service
metadata:
  name: gis262-cs4783-spring2021-db-service
spec:
  selector:
    app: cs4783-spring2021-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
